spring.application.name=backend

server.port=${PORT:8080}

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bus_booking}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis & Cache Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.timeout=500ms
spring.data.redis.connect-timeout=500ms
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Security / JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Gemini AI
gemini.api-key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-3.8-flash}

# Bakong Payment
bakong.base-url=${BAKONG_BASE_URL:https://api-bakong.nbc.gov.kh}
bakong.email=${BAKONG_EMAIL:chanheng059@gmail.com}
bakong.account-id=${BAKONG_ACCOUNT_ID:chanheng_chun1@bkrt}
bakong.merchant-name=${BAKONG_MERCHANT_NAME:TRIP-Z}
bakong.merchant-city=${BAKONG_MERCHANT_CITY:PHNOM PENH}
bakong.token=${BAKONG_TOKEN:}

# ABA Payway
aba.merchant-id=${ABA_MERCHANT_ID}
aba.public-key=${ABA_PUBLIC_KEY}
aba.private-key=${ABA_PRIVATE_KEY}
aba.payway-url=${ABA_PAYWAY_URL:https://checkout-sandbox.payway.com.kh}
aba.purchase-url=${ABA_PURCHASE_URL:https://checkout-sandbox.payway.com.kh/api/payment-gateway/v1/payments/purchase}
aba.api-key=${ABA_API_KEY}
aba.return-url=${ABA_RETURN_URL:http://localhost:8080/payment/aba/return}
aba.cancel-url=${ABA_CANCEL_URL:http://localhost:8080/payment/aba/cancel}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}